/*
 * Copyright 2026 Keel Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.keelframework.sample;

import io.keelframework.sample.mcp.tools.PetstoreTools;
import org.springframework.ai.tool.ToolCallbackProvider;
import org.springframework.ai.tool.method.MethodToolCallbackProvider;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;


/**
 * MCP Server — mcp-petstore-sample
 *
 * Generated by the Keel MCP Java archetype.
 *
 * Capabilities included via transport-streamable-mvc:
 * - JWT authentication          (keel-transport-auth)
 * - Streamable HTTP session     (keel-transport-session)
 * - Streamable HTTP channel     (keel-transport-streamable-mvc)
 * - Caffeine cache              (keel-adapter-cache-caffeine)
 *
 * The developer implements:
 * - tools/     → business logic exposed to the AI agent
 * - schemas/   → validation schemas
 * - prompts/   → MCP server prompts
 */
@SpringBootApplication(scanBasePackages = "io.keelframework.sample")
public class Application extends SpringBootServletInitializer {

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(Application.class);
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    // ── Tools — @Bean ───────────────────────────────────
    @Bean
    public ToolCallbackProvider petstoreToolsBeans(PetstoreTools tool) {
        return MethodToolCallbackProvider.builder()
                .toolObjects(tool)
                .build();
    }

}